---
title: "R Notebook"
output: html_notebook
---

## Clean Up

```{bash}
brew services stop kafka
brew services stop zookeeper

brew services start zookeeper
brew services start kafka

/usr/local/Cellar/kafka/2.1.0/bin/kafka-topics --zookeeper localhost:2181 --delete --topic tweets
/usr/local/Cellar/kafka/2.1.0/bin/kafka-topics --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic tweets

/usr/local/Cellar/kafka/2.1.0/bin/kafka-console-consumer --bootstrap-server localhost:9092 --topic tweets --from-beginning
```

## Replay Tweets (Offline Walkthrough)

```{r}
replay_tweets <- function(producer, topic = "tweets", last = data.frame(), iters = 1) {
  if (iters <= 0) return(last)
  
  tweets <- readRDS(sprintf("tweets/%03d.rds", min(iters, 20)))
  
  if (nrow(tweets) > 0) {
    tweets_subset <- dplyr::select(
      tweets,
      created_at, screen_name, text, is_retweet, favorite_count, retweet_count, media_url, location
    )
    
    for (idx in 1:nrow(tweets_subset)) {
      cat(".")
      capture.output(rkafka::rkafka.send(producer, topic, "localhost", jsonlite::toJSON(tweets_subset[idx,])))
      Sys.sleep(1)
    }
  }
  
  replay_tweets(producer, topic, tweets, iters - 1)
}

producer <- rkafka::rkafka.createProducer("localhost:9092", "sync")
replay_tweets(producer, iter = 20)
```

### Record Tweets (Offline Walkthrough)

```{r}
tweets <- list()
for (i in 1:30) {
  tweets <- produce_tweets("#rstats", producer, "tweets", tweets)
  saveRDS(tweet, paste0("tweets/", sprintf("%03d", 3), ".rds"))
}
```
