# Helper that returns the thumbnail URL for an identifier contained in the 
# USDA Pomological Watercolor Collection.
#
# Expects a thumbs.json generated by a (modified) pomtiles/pomfetch.py
# containing thumbnails scraped from the wikimedia site.
find_pomological_thumbnail_url <- function(id) {
  json <- jsonlite::fromJSON("thumbs.json")
  thumbs <- as.data.frame(json)
  thumb <- thumbs[sprintf("%04d",thumbs$id) == id,]
  
  # This version only uses the wikimedia URL.
  # When deployed, load thumbnails from wikimedia.
  thumb$url
}
